title: # Name of your blog (this will show up at the top of your page and in the RSS feed)
  Mis Discos

author: # Your name, as you want it to appear underneath each post and in the footer
  G

desc: La colecci√≥n de musica que amo, mantenida con Jekyll on Github pages

keywords: music, albums, records, collection, jekyll, static-web

repository: adrienjoly/album-shelf

google_analytics: 

# github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# additional config
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
